[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "llama-cookbook"
version = "0.0.5.post1"
authors = [
  { name="Hamid Shojanazeri", email="hamidnazeri@meta.com" },
  { name="Matthias Reso", email="mreso@meta.com" },
  { name="Geeta Chauhan", email="gchauhan@meta.com" },
]
description = "Llama-cookbook is a companion project to the Llama models. It's goal is to provide examples to quickly get started with fine-tuning for domain adaptation and how to run inference for the fine-tuned models."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Other/Proprietary License",
    "Operating System :: OS Independent",
]
dynamic = ["dependencies"]

[project.optional-dependencies]
vllm = ["vllm"]
tests = ["pytest-mock"]
auditnlg = ["auditnlg"]
langchain = ["langchain_openai", "langchain", "langchain_community"]

[project.urls]
"Homepage" = "https://github.com/meta-llama/llama-cookbook"
"Bug Tracker" = "https://github.com/meta-llama/llama-cookbook/issues"

[tool.hatch.build]
exclude = [
  "dist/*",
]

[tool.hatch.build.targets.wheel]
packages = ["src/llama_cookbook"]

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements.txt"]

[tool.pytest.ini_options]
markers = [
    "skip_missing_tokenizer: skip tests when we can not access meta-llama/Llama-2-7b-hf on huggingface hub (Log in with `huggingface-cli login` to unskip).",
]
